char HELP_TEXT[] = "Global keybinds\n"
                   "\n"
                   "    ESC       Exit\n"
                   "    ctrl-q    Exit\n"
                   "    ctrl-s    Save\n"
                   "    ctrl-c    Enter edit mode\n"
                   "    ctrl-o    Open file\n"
                   "    ctrl-n    New file\n"
                   "    ctrl-z    Undo\n"
                   "    ctrl-x    Delete line\n"
                   "    ctrl-f    Find\n"
                   "\n"
                   "    ctrl-y    Toggle split buffers\n"
                   "    ctrl-h    Switch to left buffer\n"
                   "    ctrl-l    Switch to right buffer\n"
                   "    ctrl-t    Create buffer\n"
                   "    ctrl-w    Close buffer\n"
                   "    ctrl-e    Swap buffer\n"
                   "\n"
                   "Edit mode (ctrl-c)\n"
                   "\n"
                   "    :    Enter command\n"
                   "  h/H    Move left / Move to beginning of line\n"
                   "  l/L    Move right / Move to end of line\n"
                   "  j/J    Move down / Move down by chunks\n"
                   "  k/K    Move up / Move up by chunks\n"
                   "    w    Move to next word beginning\n"
                   "    b    Move to previous word beginning\n"
                   "    i    Enter insert mode\n"
                   "    I    Goto beginning of line and enter insert mode\n"
                   "    a    Move cursor one space to the right and enter insert mode\n"
                   "    A    Goto end of line and enter insert mode\n"
                   "    s    Delete one character and enter insert mode\n"
                   "    S    Clear line and enter insert mode\n"
                   "    x    Delete one character\n"
                   "    D    Delete line segment after cursor\n"
                   "    C    Delete line segment after cursor and enter insert mode\n"
                   "    u    Undo\n"
                   "  n/N    Goto next/prev search result\n"
                   "  ;/,    Goto next/prev character in search (f/F)\n"
                   "  g/G    Goto beginning/end of file\n"
                   "\n"
                   "    d\n"
                   "         w   Delete word forward\n"
                   "         b   Delete word backward\n"
                   "         d   Delete line\n"
                   "    c\n"
                   "         w   Delete word forward and enter insert mode\n"
                   "         b   Delete word backward and enter insert mode\n"
                   "         c   Delete line and enter insert mode\n"
                   "  f/F\n"
                   "         <any>  Goto next/prev instance of that character on current line\n"
                   "";
