bg0 = "#282a36"
bg1 = "#44475a"
bg2 = "#6272a4"
fg0 = "#f8f8f2"
yellow = "#f1fa8c"
blue = "#8be9fd"
pink = "#ff79c6"
green = "#50fa7b"
aqua = "#8be9fd"
orange = "#ffb86c"
red = "#ff5555"
gray = "#6272a4"
